### ISSUE TITLE
CUDA out of memory on RTX4090

### ISSUE THREAD

**Issue by teidenzero** [Nightmare-n/DepthAnyVideo#16]
Hello,
I'm trying to run the software on the wooly_mammoth demo but I'm getting a CUDA error: out of memory on my RTX 4090 using the command `python run_infer.py --data_path ./demos/wooly_mammoth.mp4 --output_dir ./outputs/ --max_resolution 960`
any idea why this might be happening?

Thank you

**Comment by Ssecant** [comment]
I have this problem as well.

**Comment by Nightmare-n** [comment]
Please take a look at #9. You might also consider using full fp16 to further decrease memory usage.
