### ISSUE TITLE
eval code

### ISSUE THREAD

**Issue by zhizunhu** [Nightmare-n/DepthAnyVideo#19]
Hello, I found that you just use pixel level u,v multiply depth. Why not using intrinsic？
<img width="598" alt="截屏2024-10-31 16 14 33" src="https://github.com/user-attachments/assets/8ea27e20-5bdd-488c-959b-3a8e825efbe3">

**Comment by Nightmare-n** [comment]
Hi, img2lidar has incorporated the intrinsic matrix (img2lidar = cam2lidar @  np.linalg.inv(intrinsic)).
