### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by maximilian-vH** [Nightmare-n/DepthAnyVideo#2]
Thank you for your work!

What is your timeline about releasing the model weights?

**Comment by Nightmare-n** [comment]
Thank you for your patience! We plan to release the weights once the Hugging Face Space is completed, which should be around this weekend.

**Comment by NielsRogge** [comment]
Hi @Nightmare-n cool!

I indexed your paper here: https://huggingface.co/papers/2410.10815 (feel free to claim it with your HF account).

Would be cool to make the weights available on the hub in a dedicated model repo, ideally one checkpoint per model repo, see https://huggingface.co/docs/hub/models-uploading for a guide.

We can then link the models to the paper, as explained here: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper. 

Happy to assist in case you need help

**Comment by Sissi-lu** [comment]
> Thank you for your patience! We plan to release the weights once the Hugging Face Demo is completed, which should be around this weekend.

thank you!

**Comment by Nightmare-n** [comment]
Model weights are now available at https://huggingface.co/hhyangcs/depth-any-video. If you encounter any issues, please let me know.

**Comment by Nightmare-n** [comment]
> Hi @Nightmare-n cool!
> 
> I indexed your paper here: https://huggingface.co/papers/2410.10815 (feel free to claim it with your HF account).
> 
> Would be cool to make the weights available on the hub in a dedicated model repo, ideally one checkpoint per model repo, see https://huggingface.co/docs/hub/models-uploading for a guide.
> 
> We can then link the models to the paper, as explained here: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper.
> 
> Happy to assist in case you need help

Hello, I encountered an issue while uploading a model to Hugging Face Spaces. Could you please assist me in resolving it?
<img width="1119" alt="Screenshot 2024-10-19 at 22 25 40" src="https://github.com/user-attachments/assets/71cabef8-7ed9-4ba7-b79d-12f958952063">

**Comment by Nightmare-n** [comment]
> > Hi @Nightmare-n cool!
> > I indexed your paper here: https://huggingface.co/papers/2410.10815 (feel free to claim it with your HF account).
> > Would be cool to make the weights available on the hub in a dedicated model repo, ideally one checkpoint per model repo, see https://huggingface.co/docs/hub/models-uploading for a guide.
> > We can then link the models to the paper, as explained here: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper.
> > Happy to assist in case you need help
> 
> Hello @NielsRogge, I encountered an issue while uploading a model to Hugging Face Spaces. Could you please assist me in resolving it? <img alt="Screenshot 2024-10-19 at 22 25 40" width="1119" src="https://private-user-images.githubusercontent.com/47742823/378093178-71cabef8-7ed9-4ba7-b79d-12f958952063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDg0MjQsIm5iZiI6MTcyOTM0ODEyNCwicGF0aCI6Ii80Nzc0MjgyMy8zNzgwOTMxNzgtNzFjYWJlZjgtN2VkOS00YmE3LWI3OWQtMTJmOTU4OTUyMDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0Mjg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjM0MmU0ZGY4MTA1YmZiNjk1ZmRjNDRkMDI3NzI4OTE0ZDlmOGNhYzRlYTIxZjA5YWYxNzNhNWM4NWYzMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xb8LEYxr2-lZm9kmkFFNcUf6oFcCkR1hpk2KtWNoUps">

I've resolved the issue; it was caused by high memory usage.

**Comment by NielsRogge** [comment]
Hi,

Thanks for uploading the model and writing a model card. The Space looks great, too!

https://huggingface.co/papers/2410.10815 looks great :) 

Let me know if you need any help. Will ping AK to boost the visibility of your work :)
