### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory ？

### ISSUE THREAD

**Issue by juntaosun** [Nightmare-n/DepthAnyVideo#9]
```
torch.OutOfMemoryError: CUDA out of memory. See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

After testing, the input video is only 10 seconds. As expected, the GPU memory crashed. 
The model is based on Stable Video Diffusion (SVD), which requires a very high computer configuration.

For video processing, at least 24GB~48GB VRAM is required.
What is a good solution?

**Comment by Nightmare-n** [comment]
We recommend reducing the `num_frames`, `num_interp_frames`, `max_resolution`, and `decode_chunk_size` to decrease memory usage.
